import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-05-13T09:17:48.867Z

test.describe('Scenario: Landing page loads', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('https://merge-mind-one.vercel.app/');

    // Navigate to https://merge-mind-one.vercel.app
    await page.goto('https://merge-mind-one.vercel.app');

    // Assert page contains "Welcome"
    await expect(page.getByText('Welcome')).toBeVisible();

  });
});
