import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-25T02:11:37.695Z

test.describe('Scenario: Landing Page renders', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('https://merge-mind-one.vercel.app/');

    // Navigate to https://merge-mind-one.vercel.app
    await page.goto('https://merge-mind-one.vercel.app');

    // Assert page contains "Welcome to Merge Mind"
    await expect(page.getByText('Welcome to Merge Mind')).toBeVisible();

  });
});
