import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-24T22:47:44.896Z

test.describe('Scenario: Landing Page renders', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('https://merge-mind-one.vercel.app/');

    // Navigate to https://merge-mind-one.vercel.app/
    await page.goto('https://merge-mind-one.vercel.app/');

    // Assert page contains title "frontend"
    await expect(page.getByText('title "frontend')).toBeVisible();

  });
});
